---
engines:
  duplication:
    enabled: true
    exclude_paths:
    - "**test_*.py"
    - "**urls.py"
    config:
      languages:
        python:
          mass_threshold: 5
  fixme:
    enabled: true
  radon:
    enabled: true
ratings:
  paths:
  - "**.py"

exclude_paths:
- "**/migrations/*"
