language: python
dist: trusty

python:
  - "2.7"
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.6"

addons:
  postgresql: "9.6"

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -y gdal-bin

install:
  - pip install tox tox-travis

before_script:
  - psql -U postgres -c 'CREATE EXTENSION postgis'
  - psql -U postgres -c 'CREATE DATABASE test;'

script:
  - tox

after_success:
  - pip install codecov
  - codecov -e TOXENV,DJANGO
