# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-26 13:05
from __future__ import unicode_literals

import countries_flavor.fields
import django.contrib.gis.db.models.fields
import django.contrib.postgres.fields
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('cca2', countries_flavor.fields.CodeISOField(length=2, max_length=2, primary_key=True, regex='[A-Z]', serialize=False, validators=[django.core.validators.RegexValidator(regex='^[A-Z]{2}$')], verbose_name='code ISO 3166-1 alpha-2')),
                ('cca3', countries_flavor.fields.CodeISOField(length=3, max_length=3, regex='[A-Z]', validators=[django.core.validators.RegexValidator(regex='^[A-Z]{3}$')], verbose_name='code ISO 3166-1 alpha-3')),
                ('ccn3', countries_flavor.fields.CodeISOField(length=3, max_length=3, regex='\\d', validators=[django.core.validators.RegexValidator(regex='^\\d{3}$')], verbose_name='code ISO 3166-1 numeric')),
                ('cioc', countries_flavor.fields.CodeISOField(length=3, max_length=3, regex='[A-Z]', validators=[django.core.validators.RegexValidator(regex='^[A-Z]{3}$')], verbose_name='code International Olympic Committee')),
                ('location', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('geo', django.contrib.gis.db.models.fields.MultiPolygonField(null=True, srid=4326)),
                ('region', models.CharField(max_length=64, verbose_name='region')),
                ('subregion', models.CharField(max_length=64, verbose_name='subregion')),
                ('capital', models.CharField(max_length=128, verbose_name='capital')),
                ('landlocked', models.BooleanField(verbose_name='landlocked status')),
                ('demonym', models.CharField(max_length=64, verbose_name='name of residents')),
                ('area', models.PositiveIntegerField(null=True, verbose_name='land area in km')),
                ('alt_spellings', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=128), size=None, verbose_name='alternative spellings')),
                ('calling_codes', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=8, validators=[django.core.validators.RegexValidator(regex='^\\d+$')]), size=None, verbose_name='calling codes')),
                ('tlds', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=16), size=None, verbose_name='country code top-level domains')),
                ('borders', models.ManyToManyField(blank=True, related_name='_country_borders_+', to='countries_flavor.Country', verbose_name='land borders')),
            ],
            options={
                'verbose_name_plural': 'countries',
                'ordering': ('cca2',),
            },
        ),
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('code', countries_flavor.fields.CodeISOField(length=3, max_length=3, primary_key=True, regex='[A-Z]', serialize=False, validators=[django.core.validators.RegexValidator(regex='^[A-Z]{3}$')], verbose_name='code ISO 4217')),
                ('symbol', models.CharField(max_length=4, verbose_name='symbol')),
            ],
            options={
                'verbose_name_plural': 'currencies',
                'ordering': ('code',),
            },
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('name', models.CharField(max_length=64, verbose_name='name')),
                ('code', countries_flavor.fields.CodeISOField(length=3, max_length=3, primary_key=True, regex='[a-z]', serialize=False, validators=[django.core.validators.RegexValidator(regex='^[a-z]{3}$')], verbose_name='language code ISO 639-3')),
            ],
            options={
                'ordering': ('code',),
            },
        ),
        migrations.CreateModel(
            name='Translation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('common', models.CharField(max_length=128, verbose_name='common name')),
                ('official', models.CharField(max_length=128, verbose_name='official name')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='countries_flavor.Country', verbose_name='country')),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='countries_flavor.Language', verbose_name='language')),
            ],
            options={
                'ordering': ('country', 'language'),
            },
        ),
        migrations.AddField(
            model_name='country',
            name='currencies',
            field=models.ManyToManyField(to='countries_flavor.Currency', verbose_name='currencies'),
        ),
        migrations.AddField(
            model_name='country',
            name='languages',
            field=models.ManyToManyField(to='countries_flavor.Language', verbose_name='official languages'),
        ),
        migrations.AlterUniqueTogether(
            name='translation',
            unique_together=set([('country', 'language')]),
        ),
    ]
